from sqlalchemy import Column, Integer, Numeric, Unicode, Identity, UnicodeText
from sqlalchemy.dialects.mssql import DATETIME2, BIGINT
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class RptFacebookPosts(Base):
    __tablename__ = 'RptFacebookPosts'
    __table_args__ = {'schema': 'VideoStats.dbo'}

    id = Column(Integer, Identity(start=1, increment=1), primary_key=True)
    post_id = Column(BIGINT, nullable=False)
    page_id = Column(BIGINT, nullable=False)
    page_name = Column(Unicode(100), nullable=False)
    video_title = Column(UnicodeText, nullable=False)
    video_program = Column(Unicode(100), nullable=True)
    video_description = Column(Unicode(2000), nullable=True)
    video_duration_seconds = Column(Integer, nullable=False)
    video_duration_hours = Column(Numeric(18, 4), nullable=False)
    published_datetime = Column(DATETIME2, nullable=False)
    caption_type = Column(Unicode(50), nullable=True)
    permalink_url = Column(Unicode(2000), nullable=False)
    crosspost_ind = Column(Integer, nullable=False)
    share_ind = Column(Integer, nullable=False)
    post_type = Column(Unicode(50), nullable=False)
    video_view_date = Column(Unicode(100), nullable=False)
    total_views = Column(Integer, nullable=False)
    video_reach = Column(Integer, nullable=False)
    total_reactions_comments_shares = Column(Integer, nullable=False)
    total_reactions = Column(Integer, nullable=False)
    total_comments = Column(Integer, nullable=False)
    total_shares = Column(Integer, nullable=False)
    total_clicks = Column(Integer, nullable=False)
    other_clicks = Column(Integer, nullable=False)
    matched_audience_targeting_consumption = Column(Integer, nullable=False)
    link_clicks = Column(Integer, nullable=False)
    total_views_from_organic_posts = Column(Integer, nullable=False)
    total_views_from_boosted_posts = Column(Integer, nullable=False)
    video_reach_from_organic_posts = Column(Integer, nullable=False)
    video_reach_from_boosted_posts = Column(Integer, nullable=False)
    video_views_3_seconds = Column(Integer, nullable=False)
    video_views_60_seconds = Column(Integer, nullable=False)
    video_viewers_3_seconds = Column(Integer, nullable=False)
    video_viewers_60_seconds = Column(Integer, nullable=False)
    video_viewers_3_seconds_boosted = Column(Integer, nullable=False)
    video_viewers_3_seconds_organic = Column(Integer, nullable=False)
    video_views_60_seconds_recommendations = Column(Integer, nullable=False)
    video_views_60_seconds_shares = Column(Integer, nullable=False)
    video_views_60_seconds_followers = Column(Integer, nullable=False)
    video_views_60_seconds_boosted = Column(Integer, nullable=False)
    total_seconds_viewed = Column(Numeric(18, 4), nullable=False)
    total_hours_viewed = Column(Numeric(18, 4), nullable=False)
    avg_seconds_viewed = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_recommendations = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_shares = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_followers = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_boosted = Column(Numeric(18, 4), nullable=False)
    source_data_datetime = Column(DATETIME2, nullable=False)
    record_insert_datetime = Column(DATETIME2, nullable=False)
    record_update_datetime = Column(DATETIME2, nullable=True)


class StageRptFacebookPosts(Base):
    __tablename__ = 'StageRptFacebookPosts'
    __table_args__ = {'schema': 'VideoStats.dbo'}

    id = Column(Integer, primary_key=True)
    post_id = Column(BIGINT, nullable=False)
    page_id = Column(BIGINT, nullable=False)
    page_name = Column(Unicode(100), nullable=False)
    video_title = Column(UnicodeText, nullable=False)
    video_program = Column(Unicode(100), nullable=True)
    video_description = Column(Unicode(2000), nullable=True)
    video_duration_seconds = Column(Integer, nullable=False)
    video_duration_hours = Column(Numeric(18, 4), nullable=False)
    published_datetime = Column(DATETIME2, nullable=False)
    caption_type = Column(Unicode(50), nullable=True)
    permalink_url = Column(Unicode(2000), nullable=False)
    crosspost_ind = Column(Integer, nullable=False)
    share_ind = Column(Integer, nullable=False)
    post_type = Column(Unicode(50), nullable=False)
    video_view_date = Column(Unicode(100), nullable=False)
    total_views = Column(Integer, nullable=False)
    video_reach = Column(Integer, nullable=False)
    total_reactions_comments_shares = Column(Integer, nullable=False)
    total_reactions = Column(Integer, nullable=False)
    total_comments = Column(Integer, nullable=False)
    total_shares = Column(Integer, nullable=False)
    total_clicks = Column(Integer, nullable=False)
    other_clicks = Column(Integer, nullable=False)
    matched_audience_targeting_consumption = Column(Integer, nullable=False)
    link_clicks = Column(Integer, nullable=False)
    total_views_from_organic_posts = Column(Integer, nullable=False)
    total_views_from_boosted_posts = Column(Integer, nullable=False)
    video_reach_from_organic_posts = Column(Integer, nullable=False)
    video_reach_from_boosted_posts = Column(Integer, nullable=False)
    video_views_3_seconds = Column(Integer, nullable=False)
    video_views_60_seconds = Column(Integer, nullable=False)
    video_viewers_3_seconds = Column(Integer, nullable=False)
    video_viewers_60_seconds = Column(Integer, nullable=False)
    video_viewers_3_seconds_boosted = Column(Integer, nullable=False)
    video_viewers_3_seconds_organic = Column(Integer, nullable=False)
    video_views_60_seconds_recommendations = Column(Integer, nullable=False)
    video_views_60_seconds_shares = Column(Integer, nullable=False)
    video_views_60_seconds_followers = Column(Integer, nullable=False)
    video_views_60_seconds_boosted = Column(Integer, nullable=False)
    total_seconds_viewed = Column(Numeric(18, 4), nullable=False)
    total_hours_viewed = Column(Numeric(18, 4), nullable=False)
    avg_seconds_viewed = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_recommendations = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_shares = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_followers = Column(Numeric(18, 4), nullable=False)
    seconds_viewed_boosted = Column(Numeric(18, 4), nullable=False)
    source_data_datetime = Column(DATETIME2, nullable=False)